### ISSUE TITLE
Issue with single activity courses

### ISSUE THREAD

**Issue by emmafsp** [frumbert/moodle-tool_uploadactivitycompletions#2]
This plugin is exactly what I need to be able to mark completions for courses completed externally or historically by certain users. I am having a problem where the courses are Single Activity scorm courses. There is no "section" so the import fails because it can't find the activity. Is there a work around for this?

**Comment by frumbert** [comment]
Turns out there was a bug in the section name and activity name validator check that prevents the 'zero' value from being evaluated properly. During import the section name can't be found (because it doesn't exist on the first item) and therefore the record is skipped. I put in a [patch](https://github.com/frumbert/moodle-tool_uploadactivitycompletions/commit/7a9083dc904f05f31fe751ad33d79ad11fb466e0).

A single activity course
![Screen Shot 2021-07-13 at 11 53 48 am](https://user-images.githubusercontent.com/592257/125377828-01a20f00-e3d1-11eb-88f5-e88a9aa1283e.png)

A user completion record created in excel and put into the import process
![Screen Shot 2021-07-13 at 11 32 32 am](https://user-images.githubusercontent.com/592257/125377783-ec2ce500-e3d0-11eb-8d3e-5f0eb273bce2.png)

Yields a user (enrolled) and with a new completion record.
![Screen Shot 2021-07-13 at 11 49 39 am](https://user-images.githubusercontent.com/592257/125377794-f0590280-e3d0-11eb-80dd-9971637d5d93.png)

Activity completion shows the record as overridden:
![Screen Shot 2021-07-13 at 11 55 23 am](https://user-images.githubusercontent.com/592257/125377987-43cb5080-e3d1-11eb-9ff9-106dfb6718c7.png)
